src/SchoolExperienceUi/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SchoolExperienceBaseTypes;
using SchoolExperienceUi.Facades;
using SchoolExperienceUi.Models.Candidate;

namespace SchoolExperienceUi.Controllers
{
    public class CandidateController : Controller
    {
        private readonly ISchoolFacade _schoolService;
        private readonly ICandidateFacade _candidateService;

        private readonly IMapper _mapper;

        private static readonly string UserId = "11111111-1111-1111-1111-111111111111";

        public CandidateController(IMapper mapper, ISchoolFacade schoolService, ICandidateFacade candidateFacade)
        {
            _schoolService = schoolService;
            _candidateService = candidateFacade;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new IndexViewModel
            {
                Bookings = new List<IndexBookingItem>(),
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult FindSchools()
        {
            var viewModel = new FindSchoolViewModel
            {
                PostCode = "OL15 8RE",
                SearchDistanceInMiles = 1,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> FindSchools(FindSchoolViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var schools = await _schoolService.FindSchoolsAsync(viewModel.PostCode, new Distance { Miles = viewModel.SearchDistanceInMiles });
                viewModel.Schools = _mapper.Map<IEnumerable<FindSchoolViewModel.School>>(schools.Schools);
            }

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Diary()
        {
            var viewModel = new DiaryViewModel();

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Events(DateTime? start, DateTime? end)
        {
            var today = DateTime.UtcNow.Date;
            if (!start.HasValue)
            {
                start = today.StartOfMonth();
            }
            if (!end.HasValue)
            {
                end = today.EndOfMonth();
            }

            var result = await _candidateService.GetDiaryEntriesAsync(UserId, start.Value, end.Value);
            return Ok(_mapper.Map<DiaryViewModel>(result));
        }

        [HttpPost]
        public async Task<IActionResult> CreateDiaryEntry([FromBody] CreateDiaryEntryRequest request)
        {
            var result = await _candidateService.CreateDiaryEntryAsync(UserId, request.Start, request.End, DiaryEntryType.Free);

            var viewModel = _mapper.Map<CreateDiaryEventViewModel>(result);

            return Ok(viewModel);
        }

        [HttpDelete]
        public async Task<IActionResult> RemoveDiaryEntry(int id)
        {
            var result = await _candidateService.DeleteDiaryEntryAsync(UserId, id);

            return Ok(result.Result);
        }
    }
}

src/SchoolExperienceUi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SchoolExperience.Models;

namespace SchoolExperience.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SchoolExperienceUi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<main class="govuk-main-wrapper">


    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <h1 class="govuk-heading-xl">
                Get a school experience placement
            </h1>

            <p>Find and book a school experience placement with a primary or secondary school in England.</p>
            <p>To get school experience you must be:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>at least 18 years of age and thinking about becoming a teacher</li>
                <li>have or be taking a degree or equivalent overseas qualification</li>
                <li>applying for teacher training within the upcoming academic year</li>
            </ul>

            <p class="govuk-inset-text">
                This service is only available for school experience placements in England
            </p>



            <a asp-controller="Candidate" asp-action="Index" role="button" class="govuk-button govuk-button--start govuk-!-margin-top-2 govuk-!-margin-bottom-8">Start now</a>

            <h2 class="govuk-heading-m">Before you start</h2>
            <p>To help cover costs, some schools charge a fee for school experience placements. You’ll need to pay any fees direct to the individual schools.</p>
            <p>
                You’ll need to provide:
            </p>
            <ul class="govuk-list govuk-list--bullet">
                <li>personal details - including your address</li>
                <li>contact details - including your email and telephone number</li>
            </ul>


            <p>
                Some schools also require you to undergo a Disclosure and Barring Service (DBS) check.
            </p>
            <P>
                This is a safeguarding check to confirm that you’re suitable and able to work with vulnerable groups such as children.
            </P>
            <p>
                You’ll get a confirmation email after you’ve booked your school experience placement.
            </p>
        </div>

        <div class="govuk-grid-column-one-third">

            <aside class="app-related-items" role="complementary">
                <h2 class="govuk-heading-m" id="subsection-title">
                    Subsection
                </h2>
                <nav role="navigation" aria-labelledby="subsection-title">
                    <ul class="govuk-list govuk-!-font-size-16">
                        <li>
                            <a href="https://schoolexperiencebetaschool.azurewebsites.net/">
                                School site
                            </a>
                        </li>
                        <li>
                            <a href="#" class="govuk-!-font-weight-bold">
                                More <span class="govuk-visually-hidden">in Subsection</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </aside>

        </div>
    </div>

</main>


</main>