src/SchoolExperienceSchoolUi/Controllers/Auth2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace SchoolExperienceSchoolUi
{
    public class Auth2Controller : Controller
    {
        public async Task Login(string returnUrl = "/")
        {
            await HttpContext.ChallengeAsync(new AuthenticationProperties() { RedirectUri = returnUrl });
        }

        [Authorize]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        [Authorize]
        public async Task SignedIn()
        {
            await Task.CompletedTask;
        }

        /// <summary>
        /// User is signed in but does not have access ot the requested page/action.
        /// The user ends up here when the API returns a 401.
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ViewResult AccessDenied()
        {
            Response.StatusCode = (int)HttpStatusCode.Unauthorized;
            return null;// View();
        }

        /// <summary>
        /// Endpoint for registration callback.
        /// Route is configured from config in <see cref="Startup.Configure"/>
        /// </summary>
        public ActionResult RegistrationComplete()
        {
            return null;// RedirectToAction("WhoAmI");
        }
    }

    public class WhoAmIViewModel
    {
        public IEnumerable<Claim> RawClaims { get; set; }
        //public OrgClaim Org { get; set; }
    }
}

src/SchoolExperienceSchoolUi/Controllers/SampleDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SchoolExperienceSchoolUi.Controllers
{
    [Route("api/[controller]")]
    public class SampleDataController : Controller
    {
        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        [HttpGet("[action]")]
        public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                DateFormatted = DateTime.Now.AddDays(index).ToString("d"),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
        }

        public class WeatherForecast
        {
            public string DateFormatted { get; set; }
            public int TemperatureC { get; set; }
            public string Summary { get; set; }

            public int TemperatureF
            {
                get
                {
                    return 32 + (int)(TemperatureC / 0.5556);
                }
            }
        }
    }
}

src/SchoolExperienceSchoolUi/Pages/Association/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchoolExperienceSchoolUi.Pages.Association
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/SchoolExperienceSchoolUi/Pages/Components/SignInDetails/SignInDetailsViewComponent.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SchoolExperienceSchoolUi.Pages.Components.SignInDetails
{
    public class SignInDetailsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var viewModel = new ViewModel();

            if (User.Identity.IsAuthenticated)
            {
                var identity = (ClaimsIdentity)User.Identity;
                var name = identity.Claims.FirstOrDefault(x => x.Type == "given_name");
                viewModel.Name = name.Value;
                viewModel.LastSignIn = DateTime.UtcNow.AddMinutes(-37);
            }
            else
            {
                viewModel.Name = "Unknown";
            }

            return await Task.FromResult(View(viewModel));
        }
    }
}

src/SchoolExperienceSchoolUi/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchoolExperienceSchoolUi.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/SchoolExperienceSchoolUi/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SchoolExperienceSchoolUi.Facades;

namespace SchoolExperienceSchoolUi.Pages
{
    public class DashboardModel : PageModel
    {
        private readonly ISchoolFacade _schoolFacade;

        private readonly IMapper _mapper;

        public DashboardModel(ISchoolFacade schoolFacade, IMapper mapper)
        {
            _schoolFacade = schoolFacade;
            _mapper = mapper;
        }

        public int TotalAdvertised { get; set; }
        public int TotalBooked { get; set; }
        public int TotalAvailable { get; set; }

        public class SubjectPlacement
        {
            public string Name { get; set; }
            public int Count { get; set; }
        }

        public class SchoolPlacement
        {
            public string Name { get; set; }
            public int Count { get; set; }
        }

        public IEnumerable<SubjectPlacement> SubjectPlacements { get; set; }
        public IEnumerable<SchoolPlacement> SchoolPlacements { get; set; }

        public async Task OnGetAsync()
        {
            try
            {
                var stats = await _schoolFacade.GetPlacementTotals();
                TotalAdvertised = stats.TotalAdvertised;
                TotalAvailable = stats.TotalAvailable;
                TotalBooked = stats.TotalBooked;
                SubjectPlacements = stats.SubjectPlacements.Select(x => new SubjectPlacement { Name = x.Name, Count = x.Count });
                SchoolPlacements = stats.SchoolPlacements.Select(x => new SchoolPlacement { Name = x.Name, Count = x.Count });
            }
            catch(HttpRequestException ex)
            {
                TotalAdvertised = TotalAvailable = TotalBooked = -1;
                SubjectPlacements = new List<SubjectPlacement>();
                SchoolPlacements = new List<SchoolPlacement>();
            }
        }
    }
}

src/SchoolExperienceSchoolUi/Pages/ProtectedPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchoolExperienceSchoolUi.Pages
{
    [Authorize]
    public class ProtectedPageModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/SchoolExperienceSchoolUi/Pages/Association/Index.cshtml
@page
@model SchoolExperienceSchoolUi.Pages.Association.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<h2>Welcome @User.Claims.FirstOrDefault(c => c.Type == "name")?.Value</h2>

<dl>
    @foreach (var claim in User.Claims)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>
    }
</dl>

src/SchoolExperienceSchoolUi/Pages/Index.cshtml
@page
@model SchoolExperienceSchoolUi.Pages.DashboardModel

@{
    ViewData["Title"] = "Dashboard";
}

@section afterHeader
    {
    <vc:sign-in-details></vc:sign-in-details>
}

<div class="govuk-grid-row dashboard-figures">


    <div class="govuk-grid-column-one-half">


        <h1 class="govuk-heading-m">Your placements</h1>
        <div class="top-data-elements">
            <p class="govuk-!-font-size-24 key-measure">
                <em class="govuk-!-font-size-48 keyfigure">@Model.TotalAdvertised</em><br />
                Advertised
            </p>
        </div>
        <div class="top-data-elements">
            <p class="govuk-!-font-size-24 key-measure">
                <em class="govuk-!-font-size-48 keyfigure">@Model.TotalBooked</em><br />
                Booked
            </p>
        </div>
        <div class="top-data-elements">

            <p class="govuk-!-font-size-24 key-measure">
                <em class="govuk-!-font-size-48 keyfigure">@Model.TotalAvailable</em><br />
                Available
            </p>
        </div>

        @if (Model.SubjectPlacements.Any())
        {

            <table class="govuk-table">
                <caption class="govuk-table__caption">Available placements</caption>
                <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th class="govuk-table__header" scope="col">Subject</th>
                        <th class="govuk-table__header govuk-table__header--numeric" scope="col">Amount</th>
                    </tr>
                </thead>
                <tbody class="govuk-table__body">
                    @foreach (var subject in Model.SubjectPlacements)
                    {
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header" scope="row">@subject.Name</th>
                            <td class="govuk-table__cell govuk-table__cell--numeric">@subject.Count</td>
                        </tr>
                    }
                </tbody>
            </table>
        }

        @if (Model.SchoolPlacements.Any())
        {
            <table class="govuk-table">
                <caption class="govuk-table__caption">Available placements by school</caption>
                <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th class="govuk-table__header" scope="col">Name</th>
                        <th class="govuk-table__header govuk-table__header--numeric" scope="col">Amount</th>
                    </tr>
                </thead>
                <tbody class="govuk-table__body">
                    @foreach (var school in Model.SchoolPlacements)
                    {
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header" scope="row">@school.Name</th>
                            <td class="govuk-table__cell govuk-table__cell--numeric">@school.Count</td>
                        </tr>
                    }

                </tbody>
            </table>
        }

    </div>



    <div class="govuk-grid-column-one-half">

        <div class="dashboard-top-divider">
            &nbsp;
        </div>

        <div class="greyblock1">

            <h2 class="govuk-heading-m">Your associations</h2>
            <ul class="govuk-list">
                <li><a class="govuk-link" asp-page="Association/Index">View associations</a></li>
                <li><a class="govuk-link" href="/booking/add-subsidiary?id=2">Add subsidiary schools</a></li>
                <li><a class="govuk-link" href="/booking/remove-subsidiary?id=2">Remove subsidiary schools</a></li>
            </ul>

        </div>
        <div class="greyblock2">

            <h2 class="govuk-heading-m">Your placements</h2>
            <ul class="govuk-list">
                <li><a class="govuk-link" href="/booking/view-calender?id=4">View calendar</a></li>
                <li><a class="govuk-link" href="/booking/non-placements?id=4">Add non-placement days</a></li>


                <li><a class="govuk-link" href="/booking/current-placments?id=4">View live placements</a></li>
                <li><a class="govuk-link" href="/booking/manage-placements?id=4">Manage placements</a></li>

            </ul>

        </div>


        <div class="greyblock1">

            <h2 class="govuk-heading-m">Your profiles</h2>
            <ul class="govuk-list">
                <li><a class="govuk-link" href="/booking/profile?id=3">View profiles</a></li>
                <li><a class="govuk-link" href="/booking/image-management?id=3">Image management</a></li>
                <li><a class="govuk-link" href="/booking/add-content?id=3">Add content</a></li>
                <li><a class="govuk-link" href="/booking/remove-content?id=3">Remove content</a></li>
            </ul>

        </div>

        <div class="greyblock2">

            <h2 class="govuk-heading-m">Your bookings</h2>
            <ul class="govuk-list">
                <li><a class="govuk-link" href="/booking/view-bookings?id=5">View bookings</a></li>
                <li><a class="govuk-link" href="/booking/view-messages?id=5">View messages</a></li>
                <li><a class="govuk-link" href="/booking/notification?id=5">Notifications</a></li>
                <li><a class="govuk-link" href="/booking/attenedance?id=5">Candidate attendance</a></li>
            </ul>

        </div>



    </div>

</div>

src/SchoolExperienceSchoolUi/Pages/ProtectedPage.cshtml
@page
@model SchoolExperienceSchoolUi.Pages.ProtectedPageModel
@{
    ViewData["Title"] = "ProtectedPage";
}

<h2>ProtectedPage</h2>